eurazcom/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\users\solutionController as Solutions;
use App\Http\Controllers\users\realizationController as Realizations;
use App\Http\Controllers\users\eurazcomController as Eurazcom;
use App\Http\Controllers\users\contactController as Contacts;
use App\Http\Controllers\users\AppointmentController as Appointments;
use App\Http\Controllers\users\AcademyController as Academy;
use App\Http\Controllers\users\ProjectController as Projects;
use App\Http\Controllers\users\PartnerController as Partner;
use App\Http\Controllers\users\ArticleController as Articles;
use App\Http\Controllers\users\ServiceController as Services;
use App\Http\Controllers\users\ProfilController;

// admin controller
use App\Http\Controllers\admins\AdminController;
use App\Http\Controllers\admins\PartnerController;
use App\Http\Controllers\admins\AppointmentController;
use App\Http\Controllers\admins\PublicationsController;
use App\Http\Controllers\admins\CollaboratorController;
use App\Http\Controllers\admins\ProjectController;
use App\Http\Controllers\admins\RealizationsController;
  
// home
Route::get('/',[Eurazcom::class,'welcome'])->name('welcome');
Route::prefix('eurazcom')->name('eurazcom.')->group(function(){

		// services
		Route::get('/agence conception site et application web',[Services::class,'webSiteCreation'])->name('service-1');
		Route::get('/conception de logiciel specialises',[Services::class,'software'])->name('service-2');
		Route::get('/ERP integration',[Services::class,'erpIntegration'])->name('service-3');
		Route::get('/agence graphique et communication visuelle',[Services::class,'brandinDesign'])->name('service-4');
		Route::get('/agence publicitaire',[Services::class,'adverts'])->name('service-5');
		Route::get('/agence de communication et marketing',[Services::class,'marketingAndCom'])->name('service-6');
		Route::get('/consulting numerique',[Services::class,'consulting'])->name('service-7');
		Route::get('/formations',[Services::class,'trainings'])->name('service-8');
			
		// Newsletter Route
		Route::get('about',[Eurazcom::class,'about'])->name('about');
		Route::post('mewsletter',[Eurazcom::class,'newsletter'])->name('newsletter');

		// testimonials
		Route::get('testimonials',[Eurazcom::class,'testimonials'])->name('testimonials');
		Route::post('testimonials',[Eurazcom::class,'doneTestimonials'])->name('testimonial.store');

		// realization Routes
		Route::get('portfolio/all/',[Realizations::class,'getAllRealizations'])->name('portfolio');
		Route::get('portfolio/{id}/details/',[Realizations::class,'getRealizationById'])->name('portfolio.show');
		
		// partner Route
		Route::get('/partner-program',[Partner::class,'welcome'])->name('partner.home');
		Route::get('/partner/became',[Partner::class,'create'])->name('partner.create');
		Route::post('/partner/became',[Partner::class,'store'])->name('partner.store');
		Route::get('/partner/authentication',[Partner::class,'connexion'])->name('partner.connexion');
		Route::post('/partner/authentication',[Partner::class,'partnerAuthentication'])->name('partner.authentication');
		Route::get('/partner/project',[Partner::class,'project'])->name('partner.project');
		Route::post('/partner/project',[Partner::class,'storeProject'])->name('partner.project-store');
		Route::get('/partner/forgot-code',[Partner::class,'forgotCode'])->name('partner.forgotCode');
		Route::post('/partner/forgot-code',[Partner::class,'forgotCodeStore'])->name('partner.forgotCodeStore');
 
		// academy Routes
		Route::get("/academy-center",[Academy::class,'academyHome'])->name('academy');

		// project Route
		Route::get("/project",[Projects::class,'home'])->name('project.home');
		Route::get("/project/create",[Projects::class,'create'])->name('project.create');
		Route::post("/project/store",[Projects::class,'store'])->name('project.store');

		// Appointments Routes
		Route::get("appointments",[Appointments::class,'create'])->name('appointment.create');
		Route::post("appointments",[Appointments::class,'store'])->name('appointment.store');

		// Contact Routes
		Route::get("contacts",[Contacts::class,'create'])->name('contact.create');
		Route::post("contacts",[Contacts::class,'sendEmail'])->name('contact.send');

		// blog Route
		Route::get('/publications',[Articles::class,'getAllPublications'])->name('publications');
		Route::get('/publication/{publicationId}/show/{slug}/',[Articles::class,'getPublicationById'])->name('publication.show');
		Route::post('/comment/{publicationId}/doComment',[Articles::class,'commentPublication'])->name('publication.comment');
		Route::get('/publication/comment/{commentId}/edit',[Articles::class,'editComment'])->name('publication.comment.edit');
		Route::put('/comment/{commentId}/update',[Articles::class,'updateComment'])->name('publication.comment.update');
		Route::patch('/comment/{publicationId}/like',[Articles::class,'likePublication'])->name('publication.like');
		Route::post('/publications/results',[Articles::class,'searchPublications'])->name('publication.search');
		Route::get('/publications/filter',[Articles::class,'filterPublications'])->name('publications.filter');
		Route::get('/publications/categorie',[Articles::class,'categoriesFilter'])->name('publications.categoriesFilter');
		// Route::get('/publications/publish',[Articles::class,'publish'])->name('publication.publish');

		// solutions Routes
		Route::get('solutions',[Solutions::class,'getAllSolutions'])->name('solutions');
		Route::get('solutions/{id}/details',[Solutions::class,'getSolutionById'])->name('solution.show');

		// Route for only user auth
		Route::middleware(['auth:web'])->group(function(){
		Route::get('/{name}',[ProfilController::class,'welcome'])->name('profil');
		Route::get('/about/me',[ProfilController::class,'about'])->name('profil.about');
		Route::get('/profil/edit',[ProfilController::class,'edit'])->name('profil.edit');
		Route::patch('/profil/update/user',[ProfilController::class,'updateUserInfos'])->name('profil.updateUserInfos');
		Route::patch('/profil/update/avatar',[ProfilController::class,'updateUserAvatar'])->name('profil.updateUserAvatar');
 		Route::get('/profil/edit/status',[ProfilController::class,'status'])->name('profil.status');
 		Route::patch('/profil/status/updateStatus',[ProfilController::class,'updateStatus'])->name('profil.updateStatus');
 		Route::get('/profil/close/account',[ProfilController::class,'closeAccount'])->name('profil.closeAccount');
 		Route::patch('/profil/close/account',[ProfilController::class,'storeCloseAccount'])->name('profil.storeCloseAccount');
 		Route::get('/profil/password/change',[ProfilController::class,'changerPassword'])->name('profil.password');
 		Route::patch('/profil/password/change',[ProfilController::class,'updatePassword'])->name('profil.updatePassword');

		Route::get('/quotations/all',[Projects::class,'getAllProjects'])->name('profil.quotations');
 		Route::get('/quotations/current',[Projects::class,'currentProjects'])->name('quotations.current');
		Route::get('/quotations/traitement',[Projects::class,'traitement'])->name('quotations.treat');
		Route::get('/quotations/follow',[Projects::class,'follow'])->name('quotations.follow');
		Route::get('/quotations/waiting-validation',[Projects::class,'waitForValidation'])->name('quotations.waitValidation');
		Route::get("/project/{code}/view",[Projects::class,'getProjectByCode'])->name('quotation.show');

 		Route::get('/projects/all',[Projects::class,'getAllProjects'])->name('profil.projects');
		Route::get('/projects/current',[Projects::class,'currentProjects'])->name('projects.current');
		Route::get('/projects/traitement',[Projects::class,'traitement'])->name('projects.treat');
		Route::get('/projects/follow',[Projects::class,'follow'])->name('projects.follow');
 		Route::patch("/project/{code}/mark",[Projects::class,'markProject'])->name('project.mark');
 		Route::get("/project/{code}/view",[Projects::class,'getProjectByCode'])->name('project.show');
 		Route::patch("/project/{code}/approve",[Projects::class,'transform'])->name('project.approve');
	 	});

});

/*******************************************/
/*        	ADMIN ROUTES ONLY	 
/******************************************/ 
Route::prefix('admin')->name('admin.')->group(function(){

	// Route::middleware(['guest:admin'])->group(function(){
	// 	Route::get('login',[AdminController::class,'login'])->name('login');

	// });

	Route::middleware(['guest:admin'])->group(function(){
 		Route::get('welcome',[AdminController::class,'welcome'])->name('welcome');

 		// Newsletter Routes
 		Route::get('newsletter',[AdminController::class,'newsletter'])->name('newsletter');
 		// clients Routes
 		Route::get('clients',[AdminController::class,'getAllClients'])->name('clients');
 		Route::get('client/{id}/details',[AdminController::class,'getAllClientById'])->name('client.show');

 		// Admins Routes
 		Route::get('collaborators',[CollaboratorController::class,'getAllCollaborators'])->name('collaborators');
 		Route::get('collaborator/create',[CollaboratorController::class,'create'])->name('collaborator.create');
 		Route::post('collaborator/post',[CollaboratorController::class,'store'])->name('collaborator.store');
 		Route::put('collaborator/{id}/block',[CollaboratorController::class,'block'])->name('collaborator.block');

 		// Publications
 		Route::get('publications',[PublicationsController::class,'index'])->name('publications');
 		Route::get('publication/{id}/{slug}/view',[PublicationsController::class,'show'])->name('publication.show');
 		Route::get('publication/create',[PublicationsController::class,'create'])->name('publication.create');
 		Route::post('publication/store',[PublicationsController::class,'store'])->name('publication.store');

 		// contact
 		Route::get('contacts',[AdminController::class,'contacts'])->name('contacts');
 		Route::delete('contact/{id}/details',[AdminController::class,'destroy'])->name('contact.destroy');

eurazcom/app/Http/Controllers/admins/ProjectController.php
<?php

namespace App\Http\Controllers\admins;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Project;
use Illuminate\Support\Facades\Route;

class ProjectController extends Controller
{
    //get all quotations
    public function getAllQuotations()
    {
            $projects = Project::query()->with(['user'=>function($query){
                $query->select("name");
            }])->where('project',0)->get();
            return view('admin.projects.quotations.index',compact('projects'));
          
    }

    //get all projects
    public function getAllProjects()
    {
            $projects = Project::query()->with(['user'=>function($query){
                $query->select("name");
            }])->where('project',1)->get();
            return view('admin.projects.quotations.index',compact('projects'));
          
    }

    //show
    public function show($code)
    {   
     	$findProject = self::getByCode($code);
        $project = empty($findProject->users_id) ? self::getByCode($code) :  self::getByCode($code);
      	return view('admin.projects.show',compact('project'));
    }

    // edit
    public function edit($code)
    {
        $findProject = self::getByCode($code);
        $project = empty($findProject->users_id) ? self::getByCode($code) :  self::getByCode($code);
        return view('admin.projects.edit',compact('project'));
    }

    // update
    public function update(Request $request, $code)
    {
      	$this->validate($request,[
     		'budget'=>'required',
    	 ]);
    	 $project = self::getByCode($code);
      	 $project->final_budget = $request->budget;
    	 $project->status = "Waiting for validation";
    	 $project->save();
    	 return redirect()->route('admin.project.show',$project->code);
    }

    // traitement 
    public function starTraitment($code)
    {
     	$project = self::getByCode($code);
        if ($project->project == 0) {
            $project->status = "In process";
            $project->save();
        }
	 	return redirect()->back();
    }

    // download doc
    public function downloadDoc($code)
    {
    	$project = self::getByCode($code);
    }

    // livre
    public function deliver($code)
    {
        $project = self::getByCode($code);
        if ($project->start == 1) {
            $project->deliver = 1;
            $project->save();
            return redirect()->back();
        }
        return redirect()->back();
        
    }

    // start
    public function start($code)
    {
        $project = self::getByCode($code);
        if ($project->status === "Accept") {
            $project->start = 1;
            $project->save();
            return redirect()->back();
        }
        return redirect()->back();
    }

    private function getByCode($code){
    	return Project::where('code',$code)->first();
    }
}

eurazcom/resources/views/users/profil/projects/current.blade.php
@extends('users.profil.projects.master')

@section('quotations')
 <div class="col-lg-10">
	<table class="table">
		<thead>
			<tr>
				<th>#</th>
				<th>Name</th>
				<th>Activity sector</th>
				<th>Categorie</th>
				<th>Status</th>
				<th>Action</th>
			</tr>
		</thead>
		<tbody>
			@forelse($projects as $project)
    			<tr>
    				<td>
					 <button type="button" class="border-0 bg-light"
					 onclick=" 
					 	event.preventDefault();
					 	document.getElementById('mark-{{$project->code}}').submit();
					 ">
					 @if($project->mark==0)<i class="fas fa-star"></i>@else <i class="fas fa-folder"></i> @endif
					 </button>
	    				</td>
    				<td>{{$project->title}}</td>
    				<td>{{$project->activity}}</td>
    				<td>{{$project->type}}</td>
    				<td class="text-danger">
    					{{$project->status}}
    				</td>
    				<td><a href=""><i class="fa fa-eye text-dark right"></i></a></td>
    			</tr>
    			<form class="d-none" id="mark-{{$project->code}}" method="POST" 
    				action="{{route('eurazcom.project.mark',$project->code)}}">
    					@csrf
    					{{method_field('PATCH')}}
    			</form>
    		@empty
    		@endforelse
		</tbody>
	</table>
</div>
@stop

eurazcom/resources/views/users/profil/projects/follow.blade.php
@extends('users.profil.projects.master')

@section('quotations')
 <div class="col-lg-10">
	<table class="table">
		<thead>
			<tr>
				<th>#</th>
				<th>Name</th>
				<th>Activity sector</th>
				<th>Categorie</th>
				<th>Status</th>
				<th>Action</th>
			</tr>
		</thead>
		<tbody>
			@forelse($projects as $project)
    			<tr>
    				<td>
					 <button type="button" class="border-0 bg-light"
					 onclick=" 
					 	event.preventDefault();
					 	document.getElementById('mark-{{$project->code}}').submit();
					 ">
					 @if($project->mark==0)<i class="fas fa-star"></i>@else <i class="fas fa-folder"></i> @endif
					 </button>
	    				</td>
    				<td>{{$project->title}}</td>
    				<td>{{$project->activity}}</td>
    				<td>{{$project->type}}</td>
    				<td class="text-danger">
    					{{$project->status}}
    				</td>
    				<td><a href=""><i class="fa fa-eye text-dark right"></i></a></td>
    			</tr>
    			<form class="d-none" id="mark-{{$project->code}}" method="POST" 
    				action="{{route('eurazcom.project.mark',$project->code)}}">
    					@csrf
    					{{method_field('PATCH')}}
    			</form>
    		@empty
    		@endforelse
		</tbody>
	</table>
</div>
@stop

eurazcom/resources/views/users/profil/projects/index.blade.php
@extends('users.profil.projects.master')

@section('quotations')
 <div class="col-lg-10">
	<table class="table">
		<thead>
			<tr>
				<th>#</th>
				<th>Name</th>
				<th>Activity sector</th>
				<th>Categorie</th>
				<th>Status</th>
				<th>Action</th>
			</tr>
		</thead>
		<tbody>
			@forelse($projects as $project)
    			<tr>
    				<td>
					 <button type="button" class="border-0 bg-light"
					 onclick=" 
					 	event.preventDefault();
					 	document.getElementById('mark-{{$project->code}}').submit();
					 ">
					 @if($project->mark==0)<i class="fas fa-star"></i>@else <i class="fas fa-folder"></i> @endif
					 </button>
	    				</td>
    				<td>{{$project->title}}</td>
    				<td>{{$project->activity}}</td>
    				<td>{{$project->type}}</td>
    				<td class="text-danger">
    					{{$project->status}}
    				</td>
    				<td>
						<a href="{{route('eurazcom.project.show',$project->code)}}" target="__blank">
							<i class="fa fa-eye text-dark right"></i>
						</a>    					
    				</td>
    			</tr>
    			<form class="d-none" id="mark-{{$project->code}}" method="POST" 
    				action="{{route('eurazcom.project.mark',$project->code)}}">
    					@csrf
    					{{method_field('PATCH')}}
    			</form>
    		@empty
    		@endforelse
		</tbody>
	</table>
</div>
@stop

eurazcom/resources/views/users/profil/projects/master.blade.php
@extends('users.profil.layout.master')

@section('profil')
<div class="container-fluid mt-3">
	<div class="row"> 
		<div class="col-lg-2 project-sidebar mt-0">
			<nav>
				<ul>
					@if(Route::is('eurazcom.quotations.current') ||Route::is('eurazcom.quotations.treat') 	
																 ||Route::is('eurazcom.quotations.follow') ||Route::is('eurazcom.profil.quotations') ||Route::is('eurazcom.quotations.waitValidation'))
					<li><a href="{{route('eurazcom.quotations.current')}}" class="text-muted fw-bold">Attente traitement</a></li>
					<li><a href="{{route('eurazcom.quotations.treat')}}" class="text-muted fw-bold">Encours traitement</a></li>
					<li><a href="{{route('eurazcom.quotations.follow')}}" class="text-muted fw-bold">Suivis</a></li>
					<li>
						<a href="{{route('eurazcom.quotations.waitValidation')}}" class="text-muted fw-bold">
							Attente validation
						</a>
					</li>
					@else
 					<li><a href="{{route('eurazcom.projects.current')}}" class="text-muted fw-bold">Encours Realisation</a></li>
					<li><a href="{{route('eurazcom.projects.follow')}}" class="text-muted fw-bold">Suivis</a></li>
					<li><a href="{{route('eurazcom.projects.treat')}}" class="text-muted fw-bold">Livres</a></li>
					@endif
 				</ul>
			</nav>
		</div>
		@yield('quotations')
	</div>
</div>
@stop

eurazcom/resources/views/users/profil/projects/show.blade.php
<!DOCTYPE html>
<html>
<head>
	<title>{{$project->title}} - {{config('eurazcom.name')}}</title>
	<link href="{{asset('assets/vendor/bootstrap/css/bootstrap.min.css')}}" rel="stylesheet">
	 <link rel="stylesheet" href="{{asset('assets/plugins/fontawesome-free/css/all.min.css')}}">
</head>
<body class="bg-darks">
	<div class="container-fluid">
		<div class="row">
			<div class="col-lg-3 ps-5 pt-5">
				<p>Project Name : <strong> {{$project->title}}</strong></p>
				<p>Project Sector : <strong> {{$project->activity}} </strong></p>
				<p>Type of project: <strong> {{$project->type}} </strong></p>
				<p>Budget: <strong> {{$project->final_budget}} </strong></p>
			</div>
			<div class="col-lg-6 shadow" style="height: 100vh; overflow-y: scroll;">
				contenus pdf
			</div>
			<div class="col-lg-3 p-5">
			 <div class="row mb-3">
			 	<p class="mb-3">Status : <span class="text-danger fw-bold">{{$project->status}} </span></p>
  				<button type="button" class="btn btn-info btn-sm fs-5  fw-bold mb-3">
 					<i class="fa fa-download"></i> Telecharger
 				</button> 

 				
 				@if($project->project == 0)
 					<h6>Pour accepter et transmettre ce projet a notre pour un debut de realisation entrez votre addresse email.</h6>
	 				<form method="POST" action="{{route('eurazcom.project.approve',$project->code)}}">
	 					@csrf
	 					{{method_field('PATCH')}}
	 					<input type="text" name="email" class="form-control" value="{{old('email')}}" placeholder="Email addresse">
	 					<div class="text-center">
	 						<button type="submit" class="btn btn-primary btn-sm mt-3 fw-bold">Envoyer le projet</button>
	 					</div>
	 				</form>
  				@endif
  			</div>
			</div>
		</div>
	</div>
 
	<form class="d-none" id='approve-{{$project->code}}' method="POST" action="{{route('eurazcom.project.approve',$project->code)}}">
		@csrf
		{{method_field("PATCH")}}
	</form>
</body>
</html>

eurazcom/resources/views/users/profil/projects/traitement.blade.php
@extends('users.profil.projects.master')

@section('quotations')
 <div class="col-lg-10">
	<table class="table">
		<thead>
			<tr>
				<th>#</th>
				<th>Name</th>
				<th>Activity sector</th>
				<th>Categorie</th>
				<th>Status</th>
				<th>Action</th>
			</tr>
		</thead>
		<tbody>
			@forelse($projects as $project)
    			<tr>
    				<td>
					 <button type="button" class="border-0 bg-light"
					 onclick=" 
					 	event.preventDefault();
					 	document.getElementById('mark-{{$project->code}}').submit();
					 ">
					 @if($project->mark==0)<i class="fas fa-star"></i>@else <i class="fas fa-folder"></i> @endif
					 </button>
	    				</td>
    				<td>{{$project->title}}</td>
    				<td>{{$project->activity}}</td>
    				<td>{{$project->type}}</td>
    				<td class="text-danger">
    					{{$project->status}}
    				</td>
    				<td><a href=""><i class="fa fa-eye text-dark right"></i></a></td>
    			</tr>
    			<form class="d-none" id="mark-{{$project->code}}" method="POST" 
    				action="{{route('eurazcom.project.mark',$project->code)}}">
    					@csrf
    					{{method_field('PATCH')}}
    			</form>
    		@empty
    		@endforelse
		</tbody>
	</table>
</div>
@stop

eurazcom/resources/views/users/profil/projects/waiting.blade.php
@extends('users.profil.projects.master')

@section('quotations')
 <div class="col-lg-10">
	<table class="table">
		<thead>
			<tr>
				<th>#</th>
				<th>Name</th>
				<th>Activity sector</th>
				<th>Categorie</th>
				<th>Status</th>
				<th>Action</th>
			</tr>
		</thead>
		<tbody>
			@forelse($projects as $project)
    			<tr>
    				<td>
					 <button type="button" class="border-0 bg-light"
					 onclick=" 
					 	event.preventDefault();
					 	document.getElementById('mark-{{$project->code}}').submit();
					 ">
					 @if($project->mark==0)<i class="fas fa-star"></i>@else <i class="fas fa-folder"></i> @endif
					 </button>
	    				</td>
    				<td>{{$project->title}}</td>
    				<td>{{$project->activity}}</td>
    				<td>{{$project->type}}</td>
    				<td class="text-danger">
    					{{$project->status}}
    				</td>
    				<td><a href=""><i class="fa fa-eye text-dark right"></i></a></td>
    			</tr>
    			<form class="d-none" id="mark-{{$project->code}}" method="POST" 
    				action="{{route('eurazcom.project.mark',$project->code)}}">
    					@csrf
    					{{method_field('PATCH')}}
    			</form>
    		@empty
    		@endforelse
		</tbody>
	</table>
</div>
@stop