eurazcom/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\users\solutionController as Solutions;
use App\Http\Controllers\users\realizationController as Realizations;
use App\Http\Controllers\users\eurazcomController as Eurazcom;
use App\Http\Controllers\users\contactController as Contacts;
use App\Http\Controllers\users\AppointmentController as Appointments;
use App\Http\Controllers\users\AcademyController as Academy;
use App\Http\Controllers\users\ProjectController as Projects;
use App\Http\Controllers\users\PartnerController as Partner;
use App\Http\Controllers\users\ArticleController as Articles;
use App\Http\Controllers\users\ServiceController as Services;
use App\Http\Controllers\users\ProfilController;

// admin controller
use App\Http\Controllers\admins\AdminController;
use App\Http\Controllers\admins\PartnerController;
use App\Http\Controllers\admins\AppointmentController;
use App\Http\Controllers\admins\PublicationsController;
use App\Http\Controllers\admins\CollaboratorController;
use App\Http\Controllers\admins\ProjectController;
use App\Http\Controllers\admins\RealizationsController;
  
// home
Route::get('/',[Eurazcom::class,'welcome'])->name('welcome');
Route::prefix('eurazcom')->name('eurazcom.')->group(function(){

		// services
		Route::get('/agence conception site et application web',[Services::class,'webSiteCreation'])->name('service-1');
		Route::get('/conception de logiciel specialises',[Services::class,'software'])->name('service-2');
		Route::get('/ERP integration',[Services::class,'erpIntegration'])->name('service-3');
		Route::get('/agence graphique et communication visuelle',[Services::class,'brandinDesign'])->name('service-4');
		Route::get('/agence publicitaire',[Services::class,'adverts'])->name('service-5');
		Route::get('/agence de communication et marketing',[Services::class,'marketingAndCom'])->name('service-6');
		Route::get('/consulting numerique',[Services::class,'consulting'])->name('service-7');
		Route::get('/formations',[Services::class,'trainings'])->name('service-8');
			
		// Newsletter Route
		Route::get('about',[Eurazcom::class,'about'])->name('about');
		Route::post('mewsletter',[Eurazcom::class,'newsletter'])->name('newsletter');

		// testimonials
		Route::get('testimonials',[Eurazcom::class,'testimonials'])->name('testimonials');
		Route::post('testimonials',[Eurazcom::class,'doneTestimonials'])->name('testimonial.store');

		// realization Routes
		Route::get('portfolio/all/',[Realizations::class,'getAllRealizations'])->name('portfolio');
		Route::get('portfolio/{id}/details/',[Realizations::class,'getRealizationById'])->name('portfolio.show');
		
		// partner Route
		Route::get('/partner-program',[Partner::class,'welcome'])->name('partner.home');
		Route::get('/partner/became',[Partner::class,'create'])->name('partner.create');
		Route::post('/partner/became',[Partner::class,'store'])->name('partner.store');
		Route::get('/partner/authentication',[Partner::class,'connexion'])->name('partner.connexion');
		Route::post('/partner/authentication',[Partner::class,'partnerAuthentication'])->name('partner.authentication');
		Route::get('/partner/project',[Partner::class,'project'])->name('partner.project');
		Route::post('/partner/project',[Partner::class,'storeProject'])->name('partner.project-store');
		Route::get('/partner/forgot-code',[Partner::class,'forgotCode'])->name('partner.forgotCode');
		Route::post('/partner/forgot-code',[Partner::class,'forgotCodeStore'])->name('partner.forgotCodeStore');
 
		// academy Routes
		Route::get("/academy-center",[Academy::class,'academyHome'])->name('academy');

		// project Route
		Route::get("/project",[Projects::class,'home'])->name('project.home');
		Route::get("/project/create",[Projects::class,'create'])->name('project.create');
		Route::post("/project/store",[Projects::class,'store'])->name('project.store');

		// Appointments Routes
		Route::get("appointments",[Appointments::class,'create'])->name('appointment.create');
		Route::post("appointments",[Appointments::class,'store'])->name('appointment.store');

		// Contact Routes
		Route::get("contacts",[Contacts::class,'create'])->name('contact.create');
		Route::post("contacts",[Contacts::class,'sendEmail'])->name('contact.send');

		// blog Route
		Route::get('/publications',[Articles::class,'getAllPublications'])->name('publications');
		Route::get('/publication/{publicationId}/show/{slug}/',[Articles::class,'getPublicationById'])->name('publication.show');
		Route::post('/comment/{publicationId}/doComment',[Articles::class,'commentPublication'])->name('publication.comment');
		Route::get('/publication/comment/{commentId}/edit',[Articles::class,'editComment'])->name('publication.comment.edit');
		Route::put('/comment/{commentId}/update',[Articles::class,'updateComment'])->name('publication.comment.update');
		Route::patch('/comment/{publicationId}/like',[Articles::class,'likePublication'])->name('publication.like');
		Route::post('/publications/results',[Articles::class,'searchPublications'])->name('publication.search');
		Route::get('/publications/filter',[Articles::class,'filterPublications'])->name('publications.filter');
		Route::get('/publications/categorie',[Articles::class,'categoriesFilter'])->name('publications.categoriesFilter');
		// Route::get('/publications/publish',[Articles::class,'publish'])->name('publication.publish');

		// solutions Routes
		Route::get('solutions',[Solutions::class,'getAllSolutions'])->name('solutions');
		Route::get('solutions/{id}/details',[Solutions::class,'getSolutionById'])->name('solution.show');

		// Route for only user auth
		Route::middleware(['auth:web'])->group(function(){
		Route::get('/{name}',[ProfilController::class,'welcome'])->name('profil');
		Route::get('/about/me',[ProfilController::class,'about'])->name('profil.about');
		Route::get('/profil/edit',[ProfilController::class,'edit'])->name('profil.edit');
		Route::patch('/profil/update/user',[ProfilController::class,'updateUserInfos'])->name('profil.updateUserInfos');
		Route::patch('/profil/update/avatar',[ProfilController::class,'updateUserAvatar'])->name('profil.updateUserAvatar');
 		Route::get('/profil/edit/status',[ProfilController::class,'status'])->name('profil.status');
 		Route::patch('/profil/status/updateStatus',[ProfilController::class,'updateStatus'])->name('profil.updateStatus');
 		Route::get('/profil/close/account',[ProfilController::class,'closeAccount'])->name('profil.closeAccount');
 		Route::patch('/profil/close/account',[ProfilController::class,'storeCloseAccount'])->name('profil.storeCloseAccount');
 		Route::get('/profil/password/change',[ProfilController::class,'changerPassword'])->name('profil.password');
 		Route::patch('/profil/password/change',[ProfilController::class,'updatePassword'])->name('profil.updatePassword');

		Route::get('/quotations/all',[Projects::class,'getAllProjects'])->name('profil.quotations');
 		Route::get('/quotations/current',[Projects::class,'currentProjects'])->name('quotations.current');
		Route::get('/quotations/traitement',[Projects::class,'traitement'])->name('quotations.treat');
		Route::get('/quotations/follow',[Projects::class,'follow'])->name('quotations.follow');
		Route::get('/quotations/waiting-validation',[Projects::class,'waitForValidation'])->name('quotations.waitValidation');
		Route::get("/project/{code}/view",[Projects::class,'getProjectByCode'])->name('quotation.show');

 		Route::get('/projects/all',[Projects::class,'getAllProjects'])->name('profil.projects');
		Route::get('/projects/current',[Projects::class,'currentProjects'])->name('projects.current');
		Route::get('/projects/traitement',[Projects::class,'traitement'])->name('projects.treat');
		Route::get('/projects/follow',[Projects::class,'follow'])->name('projects.follow');
 		Route::patch("/project/{code}/mark",[Projects::class,'markProject'])->name('project.mark');
 		Route::get("/project/{code}/view",[Projects::class,'getProjectByCode'])->name('project.show');
 		Route::patch("/project/{code}/approve",[Projects::class,'transform'])->name('project.approve');
	 	});

});

/*******************************************/
/*        	ADMIN ROUTES ONLY	 
/******************************************/ 
Route::prefix('admin')->name('admin.')->group(function(){

	// Route::middleware(['guest:admin'])->group(function(){
	// 	Route::get('login',[AdminController::class,'login'])->name('login');

	// });

	Route::middleware(['guest:admin'])->group(function(){
 		Route::get('welcome',[AdminController::class,'welcome'])->name('welcome');

 		// Newsletter Routes
 		Route::get('newsletter',[AdminController::class,'newsletter'])->name('newsletter');
 		// clients Routes
 		Route::get('clients',[AdminController::class,'getAllClients'])->name('clients');
 		Route::get('client/{id}/details',[AdminController::class,'getAllClientById'])->name('client.show');

 		// Admins Routes
 		Route::get('collaborators',[CollaboratorController::class,'getAllCollaborators'])->name('collaborators');
 		Route::get('collaborator/create',[CollaboratorController::class,'create'])->name('collaborator.create');
 		Route::post('collaborator/post',[CollaboratorController::class,'store'])->name('collaborator.store');
 		Route::put('collaborator/{id}/block',[CollaboratorController::class,'block'])->name('collaborator.block');

 		// Publications
 		Route::get('publications',[PublicationsController::class,'index'])->name('publications');
 		Route::get('publication/{id}/{slug}/view',[PublicationsController::class,'show'])->name('publication.show');
 		Route::get('publication/create',[PublicationsController::class,'create'])->name('publication.create');
 		Route::post('publication/store',[PublicationsController::class,'store'])->name('publication.store');

 		// contact
 		Route::get('contacts',[AdminController::class,'contacts'])->name('contacts');
 		Route::delete('contact/{id}/details',[AdminController::class,'destroy'])->name('contact.destroy');

eurazcom/resources/views/admin/portfolio/create.blade.php
@extends('admin.layout.master',['title'=>'Admin Dashboad Portfolio'])

@section('master')
<div class="content-wrapper">
	<div class="content-header">
	      <div class="container-fluid">
	        <div class="row mb-2">
	          <div class="col-sm-6">
	            <h1 class="m-0 text-dark">Add Realization</h1>
	          </div><!-- /.col -->
	          <div class="col-sm-6">
	            <ol class="breadcrumb float-sm-right">
	              <li class="breadcrumb-item">
	              	<a href="{{route('admin.portfolio.index')}}" class="btn btn-primary btn-sm font-weight-bold">
		              	<i class="fa fa-plus"></i> All Realizations
	              	</a>
	              </li>
	            </ol>
	          </div> 
	        </div> 
	      </div> 
	</div>
    <section class="content">
      <div class="container-fluid">
        <div class="row">
           <div class="col-md-10 offset-1">
             <div class="card card-primary">
               <form role="form" method="POST" action="{{route('admin.portfolio.store')}}" enctype="Multipart/form-data">
               		@csrf
	                <div class="card-body">
	                	<div class="row">
		               		<div class="col-lg-6">
		               			<div class="form-group">
				                    <label for="name">Nom de la realization</label>
				                    <input type="text" class="form-control" id="name" placeholder="Enter name" name="name" value="{{old('name')}}">
				                    @error('name')<small class="text-danger">{{$message}}</small>@enderror
				                </div>
				                <div class="form-group">
				                    <label for="category">Categorie</label>
				                     <select class="form-control" name="category">
				                     	<option selected disabled>Selectionner une categorie</option>
				                     	<option value="Web Site">Site web</option>
				                     	<option value="Web Application">Application web</option>
				                     	<option value="Design">Branding & Logo design</option>
				                     	<option value="Communication">Communication</option>
				                     	<option value="Marketing">Marketing</option>
				                     	<option value="Publicite">Publicite</option>
				                     	<option value="Progiciel">Progiciel</option>
				                     </select>
				                    @error('category')<small class="text-danger">{{$message}}</small>@enderror
				                </div>
				                <div class="form-group">
				                    <label for="client">Client</label>
				                    <input type="text" class="form-control" id="client" name="client" value="{{old('client')}}" placeholder="Entrer le Client">
				                    @error('client')<small class="text-danger">{{$message}}</small>@enderror
				                </div>
				                <div class="form-group">
				                    <label for="client">Country</label>
				                    <input type="text" class="form-control" id="client" name="country" value="{{old('country')}}" placeholder="Entrer le country">
				                    @error('country')<small class="text-danger">{{$message}}</small>@enderror
				                </div>
		               		</div>
		                    <div class="col-lg-6"> 
			                  <div class="form-group">
			                    <label for="date">Date de realisation</label>
			                    <input type="date" class="form-control" id="date" name="date" value="{{old('date')}}">
			                    @error('date')<small class="text-danger">{{$message}}</small>@enderror
			                  </div>
			                  <div class="form-group">
			                    <label for="date">Url de realisation</label>
			                    <input type="text" class="form-control" id="url" name="url" value="{{old('url')}}">
			                    @error('url')<small class="text-danger">{{$message}}</small>@enderror
			                  </div>
			                  <div class="form-group">
			                    <label for="image">Image de premier plan</label>
			                    <input type="file" class="form-control" id="image" name="image" value="{{old('image')}}">
			                    @error('image')<small class="text-danger">{{$message}}</small>@enderror
			                  </div>
			                  <div class="form-group">
			                    <label for="video">Video de presentation</label>
			                    <input type="file" class="form-control" id="video" name="video" value="{{old('video')}}">
			                    @error('video')<small class="text-danger">{{$message}}</small>@enderror
			                  </div>
 		                    </div>
			             </div>
			             <div class="row">
			             	<div class="col-lg-12">
					         	<div class="form-group">
				                    <label for="image">Presentation de la realization</label>
				                    <textarea name="description" class="form-control" rows="5">{{old('description')}}</textarea>
				                    @error('description')<small class="text-danger">{{$message}}</small>@enderror
				                </div>
				            </div>
				         </div>
			         </div>
			          
	                 <div class="card-footer text-center">
	                  <button type="submit" class="btn btn-primary font-weight-bold">Ajouter au systeme</button>
	                </div>
              </form>
            </div>
           </div>
         </div>
       </div> 
    </section>
 </div>
@stop

eurazcom/resources/views/admin/portfolio/edit.blade.php
@extends('admin.layout.master',['title'=>$realization->title])

@section('master')
<div class="content-wrapper">
	<div class="content-header">
	      <div class="container-fluid">
	        <div class="row mb-2">
	          <div class="col-sm-6">
	            <h1 class="m-0 text-dark">Update Realization</h1>
	          </div><!-- /.col -->
	          <div class="col-sm-6">
	            <ol class="breadcrumb float-sm-right">
	              <li class="breadcrumb-item">
	              	<a href="{{route('admin.portfolio.index')}}" class="btn btn-primary btn-sm font-weight-bold">
		              	<i class="fa fa-plus"></i> All Realizations
	              	</a>
	              </li>
	            </ol>
	          </div> 
	        </div> 
	      </div> 
	</div>
    <section class="content">
      <div class="container-fluid">
        <div class="row">
           <div class="col-md-10 offset-1">
             <div class="card card-primary">
               <form role="form" method="POST" action="{{route('admin.portfolio.update',$realization->id)}}" enctype="Multipart/form-data">
               		@csrf
               		{{method_field('PUT')}}
	                <div class="card-body">
	                	<div class="row">
		               		<div class="col-lg-6">
		               			<div class="form-group">
				                    <label for="name">Nom de la realization</label>
				                    <input type="text" class="form-control" id="name" placeholder="Enter name" name="name" value="{{$realization->title}}">
				                    @error('name')<small class="text-danger">{{$message}}</small>@enderror
				                </div>
				                <div class="form-group">
				                    <label for="category">Categorie</label>
				                     <select class="form-control" name="category">
 				                     	<option value="Web Site">Site web</option>
				                     	<option value="Web Application" 
				                     		{{$realization->category==='Web Application'?'selected':''}}>Application web
				                        </option>
				                     	<option value="Design" 
				                     		{{$realization->category==='Design'?'selected':''}}>
				                     		Branding & Logo design
				                     	</option>
				                     	<option value="Communication" 
				                     		{{$realization->category==='Communication'?'selected':''}}>Communication
				                     	</option>
				                     	<option value="Marketing" 
				                     		{{$realization->category==='Marketing'?'selected':''}}>
				                     		Marketing
				                     	</option>
				                     	<option value="Publicite" {{$realization->category==='Publicite'?'selected':''}}>Publicite</option>
				                     	<option value="Progiciel" {{$realization->category==='Progiciel'?'selected':''}}>Progiciel</option>
				                     </select>
				                    @error('category')<small class="text-danger">{{$message}}</small>@enderror
				                </div>
				                <div class="form-group">
				                    <label for="client">Client</label>
				                    <input type="text" class="form-control" id="client" name="client" value="{{$realization->client}}" placeholder="Entrer le Client">
				                    @error('client')<small class="text-danger">{{$message}}</small>@enderror
				                </div>
				                <div class="form-group">
				                    <label for="client">Country</label>
				                    <input type="text" class="form-control" id="client" name="country" value="{{$realization->country}}" placeholder="Entrer le country">
				                    @error('country')<small class="text-danger">{{$message}}</small>@enderror
				                </div>
		               		</div>
		                    <div class="col-lg-6"> 
			                  <div class="form-group">
			                    <label for="date">Date de realisation</label>
			                    <input type="date" class="form-control" id="date" name="date" value="{{$realization->date}}">
			                    @error('date')<small class="text-danger">{{$message}}</small>@enderror
			                  </div>
			                  <div class="form-group">
			                    <label for="date">Url de realisation</label>
			                    <input type="text" class="form-control" id="url" name="url" value="{{$realization->url}}">
			                    @error('url')<small class="text-danger">{{$message}}</small>@enderror
			                  </div>
			                  <div class="form-group">
			                    <label for="image">Image de premier plan</label>
			                    <input type="file" class="form-control" id="image" name="image" value="{{$realization->image}}">
			                    @error('image')<small class="text-danger">{{$message}}</small>@enderror
			                  </div>
			                  <div class="form-group">
			                    <label for="video">Ajouter d'autres images</label>
			                    <input type="file" class="form-control" id="video" name="video" value="{{$realization->video}}">
			                    @error('video')<small class="text-danger">{{$message}}</small>@enderror
			                  </div>
 		                    </div>
			             </div>
			             <div class="row">
			             	<div class="col-lg-12">
					         	<div class="form-group">
				                    <label for="image">Presentation de la realization</label>
				                    <textarea name="description" class="form-control" rows="5">{{$realization->description}}</textarea>
				                    @error('description')<small class="text-danger">{{$message}}</small>@enderror
				                </div>
				            </div>
				         </div>
			         </div>
			          
	                 <div class="card-footer text-center">
	                  <button type="submit" class="btn btn-primary font-weight-bold">Ajouter au systeme</button>
	                </div>
              </form>
            </div>
           </div>
         </div>
       </div> 
    </section>
 </div>
@stop

eurazcom/resources/views/admin/portfolio/images.blade.php
@extends('admin.layout.master',['title'=>$realization->title])

@section('master')
<div class="content-wrapper">
	<div class="content-header">
	      <div class="container-fluid">
	        <div class="row mb-2">
	          <div class="col-sm-6">
	            <h1 class="m-0 text-dark">Ajouter de images a la Realization</h1>
	          </div><!-- /.col -->
	          <div class="col-sm-6">
	            <ol class="breadcrumb float-sm-right">
	              <li class="breadcrumb-item">
	              	<a href="{{route('admin.portfolio.index')}}" class="btn btn-primary btn-sm font-weight-bold">
		              	<i class="fa fa-plus"></i> All Realizations
	              	</a>
	              </li>
	            </ol>
	          </div> 
	        </div> 
	      </div> 
	</div>
    <section class="content">
      <div class="container-fluid">
        <div class="row">
           <div class="col-md-10 offset-1">
             <div class="card card-primary">
               <form method="POST" action="{{route('admin.portfolio.images.store',$realization->id)}}"enctype="Multipart/form-data">
               		@csrf
	                <div class="card-body">
			            <input type="hidden" name="realization" value="{{$realization->id}}">
			             <div class="row">
			             	<div class="col-lg-12">
					         	<div class="form-group">
				                    <label for="image" class="form-label">Ajouter des images a la realisation</label>
				                    <input type='file' name="images[]" class="form-control" value="{{old('images[]')}}" multiple>
				                    @error('images')<small class="text-danger">{{$message}}</small>@enderror
				                </div>
				            </div>
				         </div>
			         </div>
			          
	                 <div class="card-footer text-center">
	                  <button type="submit" class="btn btn-primary font-weight-bold">Ajouter a la realisation</button>
	                </div>
              </form>
            </div>
           </div>
         </div>
       </div> 
    </section>
 </div>
@stop

eurazcom/resources/views/admin/portfolio/index.blade.php
@extends('admin.layout.master',['title'=>'Admin Dashboad realization'])

@section('master')
<div class="content-wrapper">
	<div class="content-header">
	      <div class="container-fluid">
	        <div class="row mb-2">
	          <div class="col-sm-6">
	            <h1 class="m-0 text-dark">Realizations</h1>
	          </div><!-- /.col -->
	          <div class="col-sm-6">
	            <ol class="breadcrumb float-sm-right">
	              <li class="breadcrumb-item">
	              	<a href="{{route('admin.portfolio.create')}}" class="btn btn-primary btn-sm font-weight-bold">
		              	<i class="fa fa-plus"></i> Ajouter
	              	</a>
	              </li>
	            </ol>
	          </div> 
	        </div> 
	      </div> 
	</div>
	<section class="content">
	  <div class="container-fluid">
	    <div class="row">
	      <div class="col-12">
	        <div class="card">
	          <div class="card-body">
	            <table id="example2" class="table table-bordered table-hover">
	              <thead>
		              <tr>
 		                <th>Name</th>
		                <th>Category</th>
		                <th>Client</th>
		                <th>country</th>
		                <th>date</th>
		                <th>Url</th>
		                <th>Actions</th>
		              </tr>
	              </thead>
	              <tbody>
	              	@forelse($realizations as $realization)
		              <tr>
 		                <td>{{$realization->title}}</td>
		                <td>{{$realization->category}}</td>
		                <td>{{$realization->client}}</td>
		                <td>{{$realization->country}}</td>
		                <td>{{$realization->date}}</td>
		                <td>
		                 @if(!empty($realization->url))
                			<a href="{{$realization->url}}" target="__blank">{{substr($realization->url,11,20)}}</a>
                		 @else
                		 <i>Undefined</i>
                		 @endif
		                </td>
		                <td>
		                	<div class="row">
		                		<div class="col-lg-3">
		                			<a href="{{route('admin.portfolio.show',$realization->id)}}"><i class="fa fa-eye"></i></a>
		                		</div>
		                	</div>		                	
		                </td>
		              </tr>
	               @empty
	               	<tr>
	               		<td colspan="7" class="text-center">
	               			<img src="{{asset('assets/img/no.jpeg')}}" alt="no image" width="120">
	               			<p>Aucune realization</p>
	               		</td>
	               	</tr>
	               @endforelse
	              </tbody>
	             </table>
	          </div>
	        </div>
	       </div>
	    </div>
	  </div>
	</section>
</div>
@stop

eurazcom/resources/views/admin/portfolio/show.blade.php
@extends('admin.layout.master',['title'=>$realization->title])

@section('master')
<div class="content-wrapper">
	<div class="content-header" >
	      <div class="container-fluid">
	        <div class="row mb-0">
	          <div class="col-lg-9">
	            <h1 class="m-0 text-dark" style="font-size: 25px;">
	            	Projet {{$realization->title}} pour le compte de 
	            	<span class="font-weight-bold">{{$realization->client}}</span>
	            </h1>
	          </div><!-- /.col -->
	          <div class="col-lg-3">
	            <div class="row">
            		<div class="col-lg-3">
            			<a href="{{route('admin.portfolio.edit',$realization->id)}}" class="text-dark"><i class="fa fa-pen"></i></a>
            		</div>
            		<div class="col-lg-3">
            			<a href="{{route('admin.portfolio.images',$realization->id)}}" class="text-dark"><i class="fa fa-image"></i></a>
            		</div>
            		<div class="col-lg-3">
            			<a href="" class="text-dark"
            				onclick="if (confirm('Voulez-vous supprimer cette realization ?')) {
            					event.preventDefault();
            					document.getElementById('form-delete-{{$realization->id}}').submit();
            				}else{event.preventDefault();}">
            				<i class="fa fa-trash"></i>
            			</a>
            		</div>
	            </div>
	          </div> 
	        </div> 
	      </div> 
	</div>
	<section class="content">
	  <div class="container-fluid bg-light">
	     <div class="row">
	     	<div class="col-lg-9">
	     		<div class="mt-0 mb-4 col-lg-11 mx-auto">
	     			<img src="{{asset($realization->image)}}" alt="realization image" class="img-fluid col-lg-11">
	     		</div>
	     		<div class="mt-1">
 	     			{{$realization->description}}
	     		</div>
	     		<div class="mt-3">
	     			<h6 class="font-weight-bold mb-2 text-decoration-underline">Images associees</h6>
	     			<div class="portfolio-details-slider swiper">
		     			<div class="row swiper-wrapper">
		     				<div class="col-lg-3 mb-2 swiper-slide">
		     					<a href="{{asset($realization->image)}}" data-gallery="portfolioGallery"  class="portfolio-lightbox">
		     						<img src="{{asset($realization->image)}}" class="img-fluid rounded">
		     					</a>
		     				</div>
		     				<div class="col-lg-3 mb-2 swiper-slide">
		     					<a href="{{asset($realization->image)}}" data-gallery="portfolioGallery"  class="portfolio-lightbox">
		     						<img src="{{asset($realization->image)}}" class="img-fluid rounded">
		     					</a>
		     				</div>
		     			</div>	
		     		</div>
	     		</div>
	     	</div>
	     	<div class="col-lg-3">
	     		<div class="p-1">Name : {{$realization->title}}</div>
	     		<div class="p-1">Client : {{$realization->client??'Undefined'}}</div>
	     		<div class="p-1">Country : {{$realization->country??'Undefined'}}</div>
	     		<div class="p-1">Category : {{$realization->category}}</div>
	     		<div class="p-1">Date : {{$realization->date}}</div>
	     		<div class="p-1">URL : 
	     			@if(!empty($realization->url))
	     				<a href="{{$realization->url}}">{{substr($realization->url,11,20)}}</a> 
	     			@else 
	     				<i>Undefined</i>
	     			@endif
	     		</div>
	     		<div class="p-1">Video demo : <a href="">Regarder la video</a></div>
	     	</div>
	     </div>
	  </div>
	</section>
</div>

<form method="POST" action="{{route('admin.portfolio.delete',$realization->id)}}" id="form-delete-{{$realization->id}}" class="d-none">
	@csrf
	{{method_field("DELETE")}}
</form>
@stop