eurazcom/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\users\solutionController as Solutions;
use App\Http\Controllers\users\realizationController as Realizations;
use App\Http\Controllers\users\eurazcomController as Eurazcom;
use App\Http\Controllers\users\contactController as Contacts;
use App\Http\Controllers\users\AppointmentController as Appointments;
use App\Http\Controllers\users\AcademyController as Academy;
use App\Http\Controllers\users\ProjectController as Projects;
use App\Http\Controllers\users\PartnerController as Partner;
use App\Http\Controllers\users\ArticleController as Articles;
use App\Http\Controllers\users\ServiceController as Services;
use App\Http\Controllers\users\ProfilController;

// admin controller
use App\Http\Controllers\admins\AdminController;
use App\Http\Controllers\admins\PartnerController;
use App\Http\Controllers\admins\AppointmentController;
use App\Http\Controllers\admins\PublicationsController;
use App\Http\Controllers\admins\CollaboratorController;
use App\Http\Controllers\admins\ProjectController;
use App\Http\Controllers\admins\RealizationsController;
  
// home
Route::get('/',[Eurazcom::class,'welcome'])->name('welcome');
Route::prefix('eurazcom')->name('eurazcom.')->group(function(){

		// services
		Route::get('/agence conception site et application web',[Services::class,'webSiteCreation'])->name('service-1');
		Route::get('/conception de logiciel specialises',[Services::class,'software'])->name('service-2');
		Route::get('/ERP integration',[Services::class,'erpIntegration'])->name('service-3');
		Route::get('/agence graphique et communication visuelle',[Services::class,'brandinDesign'])->name('service-4');
		Route::get('/agence publicitaire',[Services::class,'adverts'])->name('service-5');
		Route::get('/agence de communication et marketing',[Services::class,'marketingAndCom'])->name('service-6');
		Route::get('/consulting numerique',[Services::class,'consulting'])->name('service-7');
		Route::get('/formations',[Services::class,'trainings'])->name('service-8');
			
		// Newsletter Route
		Route::get('about',[Eurazcom::class,'about'])->name('about');
		Route::post('mewsletter',[Eurazcom::class,'newsletter'])->name('newsletter');

		// testimonials
		Route::get('testimonials',[Eurazcom::class,'testimonials'])->name('testimonials');
		Route::post('testimonials',[Eurazcom::class,'doneTestimonials'])->name('testimonial.store');

		// realization Routes
		Route::get('portfolio/all/',[Realizations::class,'getAllRealizations'])->name('portfolio');
		Route::get('portfolio/{id}/details/',[Realizations::class,'getRealizationById'])->name('portfolio.show');
		
		// partner Route
		Route::get('/partner-program',[Partner::class,'welcome'])->name('partner.home');
		Route::get('/partner/became',[Partner::class,'create'])->name('partner.create');
		Route::post('/partner/became',[Partner::class,'store'])->name('partner.store');
		Route::get('/partner/authentication',[Partner::class,'connexion'])->name('partner.connexion');
		Route::post('/partner/authentication',[Partner::class,'partnerAuthentication'])->name('partner.authentication');
		Route::get('/partner/project',[Partner::class,'project'])->name('partner.project');
		Route::post('/partner/project',[Partner::class,'storeProject'])->name('partner.project-store');
		Route::get('/partner/forgot-code',[Partner::class,'forgotCode'])->name('partner.forgotCode');
		Route::post('/partner/forgot-code',[Partner::class,'forgotCodeStore'])->name('partner.forgotCodeStore');
 
		// academy Routes
		Route::get("/academy-center",[Academy::class,'academyHome'])->name('academy');

		// project Route
		Route::get("/project",[Projects::class,'home'])->name('project.home');
		Route::get("/project/create",[Projects::class,'create'])->name('project.create');
		Route::post("/project/store",[Projects::class,'store'])->name('project.store');

		// Appointments Routes
		Route::get("appointments",[Appointments::class,'create'])->name('appointment.create');
		Route::post("appointments",[Appointments::class,'store'])->name('appointment.store');

		// Contact Routes
		Route::get("contacts",[Contacts::class,'create'])->name('contact.create');
		Route::post("contacts",[Contacts::class,'sendEmail'])->name('contact.send');

		// blog Route
		Route::get('/publications',[Articles::class,'getAllPublications'])->name('publications');
		Route::get('/publication/{publicationId}/show/{slug}/',[Articles::class,'getPublicationById'])->name('publication.show');
		Route::post('/comment/{publicationId}/doComment',[Articles::class,'commentPublication'])->name('publication.comment');
		Route::get('/publication/comment/{commentId}/edit',[Articles::class,'editComment'])->name('publication.comment.edit');
		Route::put('/comment/{commentId}/update',[Articles::class,'updateComment'])->name('publication.comment.update');
		Route::patch('/comment/{publicationId}/like',[Articles::class,'likePublication'])->name('publication.like');
		Route::post('/publications/results',[Articles::class,'searchPublications'])->name('publication.search');
		Route::get('/publications/filter',[Articles::class,'filterPublications'])->name('publications.filter');
		Route::get('/publications/categorie',[Articles::class,'categoriesFilter'])->name('publications.categoriesFilter');
		// Route::get('/publications/publish',[Articles::class,'publish'])->name('publication.publish');

		// solutions Routes
		Route::get('solutions',[Solutions::class,'getAllSolutions'])->name('solutions');
		Route::get('solutions/{id}/details',[Solutions::class,'getSolutionById'])->name('solution.show');

		// Route for only user auth
		Route::middleware(['auth:web'])->group(function(){
		Route::get('/{name}',[ProfilController::class,'welcome'])->name('profil');
		Route::get('/about/me',[ProfilController::class,'about'])->name('profil.about');
		Route::get('/profil/edit',[ProfilController::class,'edit'])->name('profil.edit');
		Route::patch('/profil/update/user',[ProfilController::class,'updateUserInfos'])->name('profil.updateUserInfos');
		Route::patch('/profil/update/avatar',[ProfilController::class,'updateUserAvatar'])->name('profil.updateUserAvatar');
 		Route::get('/profil/edit/status',[ProfilController::class,'status'])->name('profil.status');
 		Route::patch('/profil/status/updateStatus',[ProfilController::class,'updateStatus'])->name('profil.updateStatus');
 		Route::get('/profil/close/account',[ProfilController::class,'closeAccount'])->name('profil.closeAccount');
 		Route::patch('/profil/close/account',[ProfilController::class,'storeCloseAccount'])->name('profil.storeCloseAccount');
 		Route::get('/profil/password/change',[ProfilController::class,'changerPassword'])->name('profil.password');
 		Route::patch('/profil/password/change',[ProfilController::class,'updatePassword'])->name('profil.updatePassword');

		Route::get('/quotations/all',[Projects::class,'getAllProjects'])->name('profil.quotations');
 		Route::get('/quotations/current',[Projects::class,'currentProjects'])->name('quotations.current');
		Route::get('/quotations/traitement',[Projects::class,'traitement'])->name('quotations.treat');
		Route::get('/quotations/follow',[Projects::class,'follow'])->name('quotations.follow');
		Route::get('/quotations/waiting-validation',[Projects::class,'waitForValidation'])->name('quotations.waitValidation');
		Route::get("/project/{code}/view",[Projects::class,'getProjectByCode'])->name('quotation.show');

 		Route::get('/projects/all',[Projects::class,'getAllProjects'])->name('profil.projects');
		Route::get('/projects/current',[Projects::class,'currentProjects'])->name('projects.current');
		Route::get('/projects/traitement',[Projects::class,'traitement'])->name('projects.treat');
		Route::get('/projects/follow',[Projects::class,'follow'])->name('projects.follow');
 		Route::patch("/project/{code}/mark",[Projects::class,'markProject'])->name('project.mark');
 		Route::get("/project/{code}/view",[Projects::class,'getProjectByCode'])->name('project.show');
 		Route::patch("/project/{code}/approve",[Projects::class,'transform'])->name('project.approve');
	 	});

});

/*******************************************/
/*        	ADMIN ROUTES ONLY	 
/******************************************/ 
Route::prefix('admin')->name('admin.')->group(function(){

	// Route::middleware(['guest:admin'])->group(function(){
	// 	Route::get('login',[AdminController::class,'login'])->name('login');

	// });

	Route::middleware(['guest:admin'])->group(function(){
 		Route::get('welcome',[AdminController::class,'welcome'])->name('welcome');

 		// Newsletter Routes
 		Route::get('newsletter',[AdminController::class,'newsletter'])->name('newsletter');
 		// clients Routes
 		Route::get('clients',[AdminController::class,'getAllClients'])->name('clients');
 		Route::get('client/{id}/details',[AdminController::class,'getAllClientById'])->name('client.show');

 		// Admins Routes
 		Route::get('collaborators',[CollaboratorController::class,'getAllCollaborators'])->name('collaborators');
 		Route::get('collaborator/create',[CollaboratorController::class,'create'])->name('collaborator.create');
 		Route::post('collaborator/post',[CollaboratorController::class,'store'])->name('collaborator.store');
 		Route::put('collaborator/{id}/block',[CollaboratorController::class,'block'])->name('collaborator.block');

 		// Publications
 		Route::get('publications',[PublicationsController::class,'index'])->name('publications');
 		Route::get('publication/{id}/{slug}/view',[PublicationsController::class,'show'])->name('publication.show');
 		Route::get('publication/create',[PublicationsController::class,'create'])->name('publication.create');
 		Route::post('publication/store',[PublicationsController::class,'store'])->name('publication.store');

 		// contact
 		Route::get('contacts',[AdminController::class,'contacts'])->name('contacts');
 		Route::delete('contact/{id}/details',[AdminController::class,'destroy'])->name('contact.destroy');

eurazcom/app/Http/Controllers/admins/PartnerController.php
<?php

namespace App\Http\Controllers\admins;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Partner;

class PartnerController extends Controller
{
    //index
    public function index($value='')
    {
    	$partners = Partner::simplepaginate(30);
    	return view("admin.partners.index",compact('partners'));
    }

    //show
    public function show($code)
    {
    	$partner = self::getPartnerByCode($code);
    	return view("admin.partners.show",compact('partner'));
    }


    //edit
    public function edit($code)
    {
    	$partner = self::getPartnerByCode($code);
    	return view("admin.partners.edit",compact('partner'));
    }

    // block
    public function block($code)
    {   
    	$partner = self::getPartnerByCode($code);
    	$partner->block == 1 ? $partner->block = 0 : $partner->block = 1;
    	$partner->save();
    	return redirect()->back();
    }

    // agree
    public function agree($code)
    {
     	$partner = self::getPartnerByCode($code);
    	$partner->accepted = 1;
    	$partner->save();
    	return redirect()->back();
    }

    // destroy partner
    public function destroy($code)
    {
    	 Partner::destroy($code);
    	 return redirect()->route('admin.partners.index');
    }

    // search partner
    public function ResultSearch()
    {      
        $query = request()->input('search');
        // return $query;
         $partners = Partner::where("name","like","$query%")->orWhere("lastname","like","$query%")
                                                            ->orWhere("code","like","$query%")
                                                            ->get();
        return view('admin.partners.ResultSearch',compact('partners'));
    }


    private function getPartnerByCode($code){
    	return Partner::where('code',$code)->first();
    }


}

eurazcom/app/Http/Controllers/users/PartnerController.php
<?php

namespace App\Http\Controllers\users;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Http\Requests\partnersRequest;
use App\Http\Requests\BusnessRequest;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Session;
use App\Models\Partner;
use App\Models\PartnerProject;
use App\Models\Request as Requests;

class PartnerController extends Controller
{
  //welcome
    public function welcome()
    {
    	return view('partners.welcome');
    }
    //welcome
    public function create()
    {
    	return view('partners.create');
    }

    // store
    public function store(Request $request)
    {
    	$partner = new Partner;
		$partner->code = matricule();
        $partner->type = $request->type;
        $partner->name = $request->name;
		$partner->lastname = $request->lastname;
		$partner->phone = $request->phone;
		$partner->email = $request->email;
		$partner->country = $request->country;
		$partner->address = $request->address;
		$partner->city = $request->city;
		$partner->cni = $request->cni_number;
	 	$partner->cni_image1 = $request->file('cni_img')->store('partners');
	 	$partner->cni_image2 = $request->file('cni_img2')->store('partners');
	 	$partner->avatar = $request->file('avatar')->store('partners');
	 	$partner->save();
	 	if ($partner != null) {
            // flashy
	 		return redirect()->route('eurazcom.partner.addConfirmation');
	 	}
     	// flashy
     	return redirect()->back();
    }

    // confirmation
     public function addConfirmation()
     {
     	 return view('partners.guest.confirmation');
     }

     // connexion 
     public function connexion()
     {
     	 return view('partners.connexion');
     }

     // send project Form
     public function project()
     {     
         $partner  = Partner::find(Session::get('code'));
         // dd($partner->code);
          return view('partners.project',compact('partner'));
     }

     // partner authentication
     public function partnerAuthentication(Request $request)
     {
     	 $this->validate($request,[
     	 	'code'=>'required',
  	 	],[
 	 		'code.exists'=>'This code is not exists o partners table'
 	 	]);
         $msg = 'Vous ne correspondez a aucun partenaire de notre agence : Entrer un code partenaire valide';
     	$partner = Partner::find($request->code);
        return $partner ? redirect()->route('eurazcom.partner.project')->with('code',$partner->code)
                        : redirect()->back()->with('warning',$msg);
        

    }

    public function storeProject(Request $request)
    {
        PartnerProject::create($request->only('clientName','clientPOBOX','clientCity','clientEmail','clientPhone','clientCountry','projectTitle','budget','categorie','currency'));
        //flashy
        return redirect()->back();
    }

    // forgot code Form
     public function forgotCode()
     {     
        return view('partners.forgotCode');
     }

     // forgot code logic function
     public function forgotCodeStore(Request $request)
     {    $this->validate($request,[
            'name' => 'required',
            'lastname' => 'required',
            'email' => 'required|email',
            'cni' => 'required',
          ]);
         Requests::create($request->only('name','lastname','email','cni'));
         return redirect()->route('welcome');
     }
  
     // find partner by her code
     private function findByCode($code){

     	return partner::where('code',$code)->first();
     }
}

eurazcom/resources/views/partners/guest/confirmation.blade.php
@extends('partners.layout.master',['title'=>'Confirmation partenaire Eurazcom'])

@section('partner')
	<div class="p-5">
  			<h3 class="mb-3 fw-bold">Votre demande a bien ete recue </h3>
			Merci d'avoir faire confiance a notre agence nous vous repondrons dans les 48h qui suivent. <br><br>

			Nous vous recommandons de communiquer notre programme de partenariat a votre entourage et tous ceux interess par notre programme dans l'optique de booster nos partenariat. 
 	</div>
@stop

eurazcom/resources/views/partners/guest/connexion.blade.php
@extends('partners.layout.master',['title'=>'Connexion partenaire Eurazcom'])

@section('partner')
	<div class="p-5">
		<h4 class="text-center fs-3 col-lg-6 mx-auto"><i class="bi bi-person-circle"></i></h4>
		<h6 class="col-lg-6 mx-auto mb-3 fw-bold text-center">Mon espace partenaire</h6>
 		<form method="POST" action="{{route('eurazcom.partner.sing-in')}}" class="col-lg-6 mx-auto">
 			@csrf
 			<div class="form-group mb-3">
 				<input type="text" name="identifiantPartners" value="{{old('identifiantPartners')}}" placeholder="Email address" class="form-control">
 			</div>
 			<div class="form-group mb-3">
 				<input type="password" name="password" value="{{old('password')}}" placeholder="Mot de passe" class="form-control">
 			</div>
 			<div class="form-group mb-3 text-center">
 				<a href="{{route('eurazcom.partner.passwordForm')}}">J'ai oublie mon mot de passe</a>
 			</div>
 			<div class="text-center mb-5">
 				<button type="submit" class="btn btn-primary btn-sm fw-bold">Connexion</button>
 			</div>
 			<div class="form-group mb-3 text-center">
 				<a href="{{route('eurazcom.partner.passwordForm')}}">J'ai oublie mon mot de passe</a>
 			</div>
 		</form>
 	</div>
@stop

eurazcom/resources/views/partners/guest/create.blade.php
@extends('partners.layout.master',['title'=>'Devenir partenaire Eurazcom'])
@section('type-section')
<link rel="stylesheet" type="text/css" href="{{asset('assets/css/multiple.css')}}">
@endsection
@section('partner')
 <div class="container-fluid">
 	<form class="register-form" method="POST" action="{{route('eurazcom.partner.store')}}" enctype="Multipart/form-data">
 		@csrf
 		<div class="form-section">
 			<h3 class="fs-5 mb-5">Quel type de partenariat souhaitez-vous ?</h3>
 			<div class="row">
 				<div class="col">
 					<label class="form-label" for="apf">
 						<img src="{{asset('assets/img/partner.png')}}">
 						<legend class="fs-6 fw-bold">Apporteur d'Affaire</legend>
 					</label>
  					<input type="radio" name="type" class="form-check" id="apf" checked>
  				</div>
 				<div class="col">
 					<label class="form-label" for="dist">
 						<img src="{{asset('assets/img/partner.png')}}">
 						<legend class="fs-6 fw-bold">Distributeur de solution</legend>
 					</label>
 					<input type="radio" name="type" class="form-check" id="dist">
 				</div>
 			</div>
 		</div>

 		<div class="form-section">
 			<h3 class="fs-5 mb-5 fw-bold">Informations D'identification personnelle</h3>
 			<div class="row">
 				<div class="col">
 					<div class="form-group mb-3">
 						<input type="text" name="name" value="{{old('name')}}" class="form-control" placeholder="Name" required>
 					</div>
 					<div class="form-group mb-3">
 						<input type="text" name="email" value="{{old('email')}}" class="form-control" placeholder="Email address" required>
 					</div>
 					<div class="form-group mb-3">
 						<input type="text" name="city" value="{{old('city')}}" class="form-control" placeholder="Your city" required>
 					</div>
 				</div>
 				<div class="col">
 					<div class="form-group mb-3">
 						<input type="text" name="lastname" value="{{old('lastname')}}" class="form-control" placeholder="Last Name" required>
 					</div>
 					<div class="form-group mb-3">
 						<input type="text" name="phone" value="{{old('phone')}}" class="form-control" id="phone" required>
 						<span id="error-msg" class="hide text-danger"></span>
 					</div>
 					<div class="form-group mb-3">
 						<select name="country" class="form-select">
							@foreach(allCountries() as $key=>$country)
                              <option value="{{$country}}" 
                                {{geolocate()->iso_code == $key? 'selected':''}}>
                                {{$country}}
                              </option>
                            @endforeach
						</select>
 					</div>
 				</div>
 			</div>
 		</div>

 		<div class="form-section">
 			<h3 class="fs-5 mb-5 fw-bold">Informations De Confirmation de votre identite</h3>
 			<div class="row">
 				<div class="col">
 					<div class="form-group mb-4">
 						<input type="text" name="address" value="{{old('address')}}" class="form-control" placeholder="Your address" required>
 					</div>
 					<div class="form-group mb-4">
 						<label class="form-label fs-6">Photo CNI/Passport</label>
 						<input type="file" name="cni_img" value="{{old('cni_img')}}" class="form-control" required>
 					</div>
 				</div>
 				<div class="col">
 					<div class="form-group mb-4">
 						<input type="number" name="cni_number" value="{{old('cni_number')}}" class="form-control" placeholder="Numero de la CNI" required>
 					</div>
 					<div class="form-group mb-4">
 						<label class="form-label fs-6">Photo CNI/Passport</label>
 						<input type="file" name="cni_img2" value="{{old('cni_img2')}}" class="form-control" required>
 					</div>
 				</div>
 			</div>
 		</div>

 		<div class="form-section">
 			<h3 class="fs-5 mb-5 fw-bold">Photo de profil</h3>
 			 <label class="form-label">Photo de profil</label>
       <input type="file" name="avatar" class="form-control" value="{{old('avatar')}}">
 		</div>

 		<div class="form-navigation  mt-5">
			<button type="button" class="previous btn btn-danger btn-sm fw-bold  float-left">Precedent</button>
			<button type="button" class="next btn btn-info btn-sm fw-bold  float-right">Suivant</button>
			<button type="submit" class="btn btn-primary fw-bold  btn-sm">Envoyer votre demande</button>
		</div>
 	</form>
 </div>
@stop

@section('registerJs')
  <script type="text/javascript" src="{{asset('assets/js/register.js')}}"></script>
@stop

eurazcom/resources/views/partners/guest/forgotpassword.blade.php
@extends('partners.layout.master',['title'=>'Mot de passe oublie'])

@section('partner')
	<div class="p-5">
		<h4 class="text-center fs-3 col-lg-6 mx-auto"><i class="bi bi-person-circle"></i></h4>
		<h6 class="col-lg-6 mx-auto mb-3 fw-bold text-center">Changer de mot de passe </h6>
 		<form method="POST" action="{{route('eurazcom.partner.verify')}}" class="col-lg-6 mx-auto">
 			@csrf
 			<div class="form-group mb-3">
 				<input type="text" name="email" value="{{old('email')}}" placeholder="Email address" class="form-control">
 				@error('email')<small class="text-danger">{{$message}}</small>@enderror
 			</div>
 			<div class="form-group mb-3">
 				<input type="text" name="code" value="{{old('code')}}" placeholder="Code partner" class="form-control">
 				@error('code')<small class="text-danger">{{$message}}</small>@enderror
 			</div>
 
 			<div class="text-center mb-5">
 				<button type="submit" class="btn btn-primary btn-sm fw-bold">Envoyer</button>
 			</div>

 		</form>
 	</div>
@stop

eurazcom/resources/views/partners/guest/mailConfirmationSend.blade.php
@extends('partners.layout.master',['title'=>'Mail confirmation send'])

@section('partner')
	<div class="p-5 text-center">
 			<h3 class="mb-3 fw-bold text-center">
 				<i class="bi bi-envelope-check text-success"></i>
 			</h3>
			Un lien de changement de mot de passe vous a ete envoye par mail. <br> <br>

			Consulter le et activez le lien afin de debuter la modification effective de votre mot de passe. Si vous ne retrouvez pas cela dans votre boite email, consulter vos spams ou cliquez sur le bouton ci-dessous pour recevoir de nouveau le lien. <br> <br>

			<form method="POST" action="{{route('eurazcom.	partner.verify')}}">
				@csrf
				<input type="hidden" name="email" value="{{old('email')}}">
				<input type="hidden" name="code" value="{{old('code')}}">

				<button type="submit" class="btn btn-primary btn-sm fw-bold">Envoyer de nouveau le lien</button>
			</form>
 	</div>
@stop

eurazcom/resources/views/partners/guest/newPasswordForm.blade.php
@extends('partners.layout.master',['title'=>'Enter new password'])

@section('partner')
	<div class="p-5">
		<h4 class="text-center fs-3 col-lg-6 mx-auto"><i class="bi bi-person-circle"></i></h4>
		<h6 class="col-lg-6 mx-auto mb-3 fw-bold text-center">Changer de mot de passe </h6>
 		<form method="POST" action="{{route('partner.updatePassword')}}" class="col-lg-6 mx-auto">
 			@csrf
 			<div class="form-group mb-3">
 				<input type="password" name="password" value="{{old('password')}}" placeholder="New password" class="form-control">
 				@error('password')<small class="text-danger">{{$message}}</small>@enderror
 			</div>
 			<div class="form-group mb-3">
 				<input type="password" name="c_password" value="{{old('c_password')}}" placeholder="Confirm new password" class="form-control">
 				@error('c_password')<small class="text-danger">{{$message}}</small>@enderror
 			</div>

 			<input type="hidden" name="code" value="{{old($verification_code)}}">
 
 			<div class="text-center mb-5">
 				<button type="submit" class="btn btn-primary btn-sm fw-bold">Changer</button>
 			</div>

 		</form>
 	</div>
@stop